### ISSUE TITLE
Bot not interacting to !price command

### ISSUE THREAD

**Issue by jimango** [Safemoon-Protocol/Discord-Bot#10]
Actually this is not an issue for me but rather an addition to the HOWTO that I figured out.
I didnt bother to write an issue about this in the beginning, but as I now figured it out I hope this can make the same process a bit easier for others.

To make the installation of the bot work and run properly there are a few more steps that I would like to share with others whom are more new to these kind of codes.

Correct me if this is not the right way of solving this.

- Configure your config.json file and put it into the /src folder.
- "default command prefix". Here you put in the "!" mark or what ever you feel as having for the command. If you run several pricebots I guess you can add "!safe" here to make it activated at !safeprice command in chat. Again correct me if im wrong, I have not tested this myself yet.
- make sure you have installed mongodb at the machine where you run this.

I hope this will help others as it helped me.
If some of the info here is wrong feel free to correct me.

regards

**Comment by reecebenson** [comment]
Hi @jimango,

> Configure your config.json file and put it into the /src folder.

That's correct, I've added a convenient `config.example.json` file so that you can copy & rename this.

> "default command prefix". Here you put in the "!" mark or what ever you feel as having for the command. If you run several pricebots I guess you can add "!safe" here to make it activated at !safeprice command in chat. Again correct me if im wrong, I have not tested this myself yet.

If you set the `prefix` to `!safe` or something similar, you'll be able to use it as you've specified (i.e. `!safeprice`).

> make sure you have installed mongodb at the machine where you run this.

If you're familiar with Docker, I have added a `docker-compose.yml` so you no longer require Mongo to be installed on your local machine, and instead it'll use Mongo inside of the container.

Cheers
