### ISSUE TITLE
Why don’t you monitor your own safemoon-protocol solidity contract repository?

### ISSUE THREAD

**Issue by Jovonni** [Safemoon-Protocol/Discord-Bot#19]
Located here:

https://github.com/safemoonprotocol/Safemoon.sol

Did your team create this above repo, or is this community made?

why is this repository listed on another account other than the official safemoon account?

Lastly, a few of us are wondering where the logic for dispersing rewards/reflections is located? It isn't in the contract itself. Is this a manual process for you, or is there another contract that is invoked?

Do you plan on creating a repo on your official GitHub account holding the smart contract itself?

Thanks in advance team 🚀

**Comment by reecebenson** [comment]
I'm not apart of the SafeMoon team but hopefully I can answer this correctly.

Yes, that link _was_ the official repository for the SafeMoon contract. My assumption as to why both `safemoonprotocol` and `safemoon-protocol` accounts exist is because the former is a regular GitHub account and the latter is an organisation account. 

My other assumption is that the latter came after when they announced some projects would be made open source (i.e. this discord bot).

> Do you plan on creating a repo on your official GitHub account holding the smart contract itself?

You can now find the organisation-held repository of the exact same contract [here](https://github.com/Safemoon-Protocol/safemoon.sol).

> Lastly, a few of us are wondering where the logic for dispersing rewards/reflections is located? It isn't in the contract itself. Is this a manual process for you, or is there another contract that is invoked?

This is irrelevant to this repository, so please ask over on the [Discord server](https://discord.gg/safemoon) inside of `#ama-questions` when the channel is unlocked.

Cheers!

**Comment by Jovonni** [comment]
Thanks for the response, I posted the issue for answers in the new repo, with a bit more technical clarity. I'm sure they'll help me out eventually. 

 @reecebenson  🚀

https://github.com/Safemoon-Protocol/safemoon.sol/issues/1

**Comment by reecebenson** [comment]
Off-topic
