### ISSUE TITLE
Custom Price Watch Interval feature

### ISSUE THREAD

**Issue by ernest-rudnicki** [Safemoon-Protocol/Discord-Bot#25]
Hello, 

I would like to point out one cool feature, that would allow people to set their own interval for `price-watch-job` and `price-watch-single-job`.

For instance, I would like to have the stats posted every 24 hours, and the price every hour, as I would like to avoid the bot spamming on the channel. Right now, I saw that it's hardcoded.

Probably, the bot would need two additional commands for the Administrator.  `!statsInterval` and `!priceInterval`.

If you accept this feature, I would be happy to work on it and create a Pull Request, as it would be my first contribution to the open source project.

**Comment by reecebenson** [comment]
Hi @Terminatt,

Great idea! If you could base a feature branch from my currently open draft PR (branch name: `feature/moderation`), that would be perfect, as I've adjusted the logic around jobs and how they're handled for guilds (so that guild owners can disable / enable specific jobs that are controllable by guilds).

Please consider on the job that it must handle both sharded and non-sharded clients for Discord. Feel free to DM me on Discord if you have any questions, my username is Simple#9999

Cheers!
